# Change these first
owner: dragon-fish # Your GitHub organization or username, where this repository lives
repo: moegirl-uptime # The name of this repository

sites:
  - name: Moegirl(zh) Mainpage
    url: https://zh.moegirl.org.cn/Mainpage
  - name: Moegirl(zh) API
    url: https://zh.moegirl.org.cn/api.php?format=json&action=query&meta=siteinfo
  - name: Moegirl(commons) Mainpage
    url: https://commons.moegirl.org.cn/Mainpage

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: dragon-fish.github.io
  baseUrl: /moegirl-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Moegirl Uptime
  introTitle: "**萌娘百科** uptime"
  introMessage: This is an unofficial uptime website for 萌娘百科
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
